
  name: servuo
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Single-line elevator pitch for your amazing snap # 79 char long summary
  description: |
    ServUO is a server emulator for the Ultima Online MMORPG. UO was one of the
    original MMORPG's, with an original release date of 1997. It still boasts an
    active community both on the Broadsword hosted shards and private hosted shards.
    ServUO is written in C# and very easy to compile and modify.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
